// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calendar.proto

package calendar_data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Calendar struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Years                []*Year  `protobuf:"bytes,2,rep,name=Years,proto3" json:"Years,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calendar) Reset()         { *m = Calendar{} }
func (m *Calendar) String() string { return proto.CompactTextString(m) }
func (*Calendar) ProtoMessage()    {}
func (*Calendar) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0}
}

func (m *Calendar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calendar.Unmarshal(m, b)
}
func (m *Calendar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calendar.Marshal(b, m, deterministic)
}
func (m *Calendar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calendar.Merge(m, src)
}
func (m *Calendar) XXX_Size() int {
	return xxx_messageInfo_Calendar.Size(m)
}
func (m *Calendar) XXX_DiscardUnknown() {
	xxx_messageInfo_Calendar.DiscardUnknown(m)
}

var xxx_messageInfo_Calendar proto.InternalMessageInfo

func (m *Calendar) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Calendar) GetYears() []*Year {
	if m != nil {
		return m.Years
	}
	return nil
}

type Year struct {
	Number               int32    `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	Months               []*Month `protobuf:"bytes,2,rep,name=Months,proto3" json:"Months,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Year) Reset()         { *m = Year{} }
func (m *Year) String() string { return proto.CompactTextString(m) }
func (*Year) ProtoMessage()    {}
func (*Year) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{1}
}

func (m *Year) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Year.Unmarshal(m, b)
}
func (m *Year) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Year.Marshal(b, m, deterministic)
}
func (m *Year) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Year.Merge(m, src)
}
func (m *Year) XXX_Size() int {
	return xxx_messageInfo_Year.Size(m)
}
func (m *Year) XXX_DiscardUnknown() {
	xxx_messageInfo_Year.DiscardUnknown(m)
}

var xxx_messageInfo_Year proto.InternalMessageInfo

func (m *Year) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Year) GetMonths() []*Month {
	if m != nil {
		return m.Months
	}
	return nil
}

type Month struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Days                 []*Day   `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Month) Reset()         { *m = Month{} }
func (m *Month) String() string { return proto.CompactTextString(m) }
func (*Month) ProtoMessage()    {}
func (*Month) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{2}
}

func (m *Month) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Month.Unmarshal(m, b)
}
func (m *Month) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Month.Marshal(b, m, deterministic)
}
func (m *Month) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Month.Merge(m, src)
}
func (m *Month) XXX_Size() int {
	return xxx_messageInfo_Month.Size(m)
}
func (m *Month) XXX_DiscardUnknown() {
	xxx_messageInfo_Month.DiscardUnknown(m)
}

var xxx_messageInfo_Month proto.InternalMessageInfo

func (m *Month) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Month) GetDays() []*Day {
	if m != nil {
		return m.Days
	}
	return nil
}

type Day struct {
	Number               int32    `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Day) Reset()         { *m = Day{} }
func (m *Day) String() string { return proto.CompactTextString(m) }
func (*Day) ProtoMessage()    {}
func (*Day) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{3}
}

func (m *Day) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Day.Unmarshal(m, b)
}
func (m *Day) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Day.Marshal(b, m, deterministic)
}
func (m *Day) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Day.Merge(m, src)
}
func (m *Day) XXX_Size() int {
	return xxx_messageInfo_Day.Size(m)
}
func (m *Day) XXX_DiscardUnknown() {
	xxx_messageInfo_Day.DiscardUnknown(m)
}

var xxx_messageInfo_Day proto.InternalMessageInfo

func (m *Day) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Day) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Calendar)(nil), "calendar_data.Calendar")
	proto.RegisterType((*Year)(nil), "calendar_data.Year")
	proto.RegisterType((*Month)(nil), "calendar_data.Month")
	proto.RegisterType((*Day)(nil), "calendar_data.Day")
}

func init() { proto.RegisterFile("calendar.proto", fileDescriptor_e3d25d49f056cdb2) }

var fileDescriptor_e3d25d49f056cdb2 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4e, 0xcc, 0x49,
	0xcd, 0x4b, 0x49, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x85, 0xf1, 0xe3, 0x53,
	0x12, 0x4b, 0x12, 0x95, 0x5c, 0xb9, 0x38, 0x9c, 0xa1, 0x02, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x29,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x9e, 0x29, 0x42, 0x9a, 0x5c, 0xac, 0x91, 0xa9,
	0x89, 0x45, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xc2, 0x7a, 0x28, 0x5a, 0xf5, 0x40,
	0x72, 0x41, 0x10, 0x15, 0x4a, 0x3e, 0x5c, 0x2c, 0x20, 0x86, 0x90, 0x18, 0x17, 0x9b, 0x5f, 0x69,
	0x6e, 0x52, 0x6a, 0x11, 0xd8, 0x18, 0xd6, 0x20, 0x28, 0x4f, 0x48, 0x87, 0x8b, 0xcd, 0x37, 0x3f,
	0xaf, 0x24, 0x03, 0x66, 0x96, 0x08, 0x9a, 0x59, 0x60, 0xc9, 0x20, 0xa8, 0x1a, 0x25, 0x67, 0x2e,
	0x56, 0x30, 0x4b, 0x48, 0x88, 0x8b, 0xc5, 0x2f, 0x31, 0x37, 0x15, 0xea, 0x26, 0x30, 0x5b, 0x48,
	0x8d, 0x8b, 0x25, 0x25, 0xb1, 0x12, 0x66, 0x90, 0x10, 0x9a, 0x41, 0x2e, 0x89, 0x95, 0x41, 0x60,
	0x79, 0x25, 0x43, 0x2e, 0x66, 0x97, 0xc4, 0x4a, 0x9c, 0x2e, 0x82, 0x19, 0xcd, 0x84, 0x30, 0x3a,
	0x89, 0x0d, 0x1c, 0x44, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xa1, 0x9f, 0xb2, 0x34,
	0x01, 0x00, 0x00,
}
